/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author netoi
 */
public class TelaPesquisaVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public TelaPesquisaVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTopo = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        btnPesquisarPerfil = new javax.swing.JButton();
        btnPesquisarPesquisar = new javax.swing.JButton();
        btnPesquisarEquipe = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        checkMasc = new javax.swing.JCheckBox();
        checkMasc2 = new javax.swing.JCheckBox();
        checkMasc1 = new javax.swing.JCheckBox();
        checkMasc3 = new javax.swing.JCheckBox();
        checkMasc4 = new javax.swing.JCheckBox();
        lblNome1 = new javax.swing.JLabel();
        checkMasc5 = new javax.swing.JCheckBox();
        checkMasc6 = new javax.swing.JCheckBox();
        checkMasc7 = new javax.swing.JCheckBox();
        lblNome2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlEquipe7 = new javax.swing.JPanel();
        lblNJogadores6 = new javax.swing.JLabel();
        lblEnderecoEquipe6 = new javax.swing.JLabel();
        lblNomeDaEquipe6 = new javax.swing.JLabel();
        lblEsporteEquipe6 = new javax.swing.JLabel();
        lblCidadeEquipe6 = new javax.swing.JLabel();
        fundo6 = new javax.swing.JLabel();
        pnlEquipe6 = new javax.swing.JPanel();
        lblNJogadores5 = new javax.swing.JLabel();
        lblEnderecoEquipe5 = new javax.swing.JLabel();
        lblNomeDaEquipe5 = new javax.swing.JLabel();
        lblEsporteEquipe5 = new javax.swing.JLabel();
        lblCidadeEquipe5 = new javax.swing.JLabel();
        fundo5 = new javax.swing.JLabel();
        pnlEquipe5 = new javax.swing.JPanel();
        lblNJogadores4 = new javax.swing.JLabel();
        lblEnderecoEquipe4 = new javax.swing.JLabel();
        lblNomeDaEquipe4 = new javax.swing.JLabel();
        lblEsporteEquipe4 = new javax.swing.JLabel();
        lblCidadeEquipe4 = new javax.swing.JLabel();
        fundo4 = new javax.swing.JLabel();
        pnlEquipe4 = new javax.swing.JPanel();
        lblNJogadores2 = new javax.swing.JLabel();
        lblEnderecoEquipe2 = new javax.swing.JLabel();
        lblNomeDaEquipe2 = new javax.swing.JLabel();
        lblEsporteEquipe2 = new javax.swing.JLabel();
        lblCidadeEquipe2 = new javax.swing.JLabel();
        fundo2 = new javax.swing.JLabel();
        pnlEquipe3 = new javax.swing.JPanel();
        lblNJogadores3 = new javax.swing.JLabel();
        lblEnderecoEquipe3 = new javax.swing.JLabel();
        lblNomeDaEquipe3 = new javax.swing.JLabel();
        lblEsporteEquipe3 = new javax.swing.JLabel();
        lblCidadeEquipe3 = new javax.swing.JLabel();
        fundo3 = new javax.swing.JLabel();
        pnlEquipe2 = new javax.swing.JPanel();
        lblNJogadores1 = new javax.swing.JLabel();
        lblEnderecoEquipe1 = new javax.swing.JLabel();
        lblNomeDaEquipe1 = new javax.swing.JLabel();
        lblEsporteEquipe1 = new javax.swing.JLabel();
        lblCidadeEquipe1 = new javax.swing.JLabel();
        fundo1 = new javax.swing.JLabel();
        pnlEquipe1 = new javax.swing.JPanel();
        lblNJogadores = new javax.swing.JLabel();
        lblEnderecoEquipe = new javax.swing.JLabel();
        lblNomeDaEquipe = new javax.swing.JLabel();
        lblEsporteEquipe = new javax.swing.JLabel();
        lblCidadeEquipe = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ArenaAPP");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ArenaAPP-Logo.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuTopo.setLayout(null);

        btnHome.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        menuTopo.add(btnHome);
        btnHome.setBounds(30, 10, 100, 30);

        Logo.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logo.setText("ArenaAPP");
        menuTopo.add(Logo);
        Logo.setBounds(40, 10, 110, 30);

        btnPesquisarPerfil.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnPesquisarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarPerfil.setText("Perfil");
        btnPesquisarPerfil.setBorderPainted(false);
        btnPesquisarPerfil.setContentAreaFilled(false);
        btnPesquisarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPerfilActionPerformed(evt);
            }
        });
        menuTopo.add(btnPesquisarPerfil);
        btnPesquisarPerfil.setBounds(832, 10, 90, 30);

        btnPesquisarPesquisar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnPesquisarPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarPesquisar.setText("Pesquisar");
        btnPesquisarPesquisar.setBorderPainted(false);
        btnPesquisarPesquisar.setContentAreaFilled(false);
        btnPesquisarPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPesquisarActionPerformed(evt);
            }
        });
        menuTopo.add(btnPesquisarPesquisar);
        btnPesquisarPesquisar.setBounds(540, 10, 130, 30);

        btnPesquisarEquipe.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnPesquisarEquipe.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarEquipe.setText("Equipe");
        btnPesquisarEquipe.setBorderPainted(false);
        btnPesquisarEquipe.setContentAreaFilled(false);
        btnPesquisarEquipe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarEquipeActionPerformed(evt);
            }
        });
        menuTopo.add(btnPesquisarEquipe);
        btnPesquisarEquipe.setBounds(680, 10, 140, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-menu-topo.png"))); // NOI18N
        menuTopo.add(jLabel4);
        jLabel4.setBounds(0, 0, 960, 50);

        getContentPane().add(menuTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        jPanel3.setLayout(null);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(10, 10, 240, 30);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(70, 50, 110, 23);

        checkMasc.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc.setText("Basquete");
        checkMasc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMascActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc);
        checkMasc.setBounds(10, 240, 120, 30);

        checkMasc2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc2.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc2.setText("Futebol");
        checkMasc2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMasc2ActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc2);
        checkMasc2.setBounds(10, 120, 120, 30);

        checkMasc1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc1.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc1.setText("Futsal");
        checkMasc1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMasc1ActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc1);
        checkMasc1.setBounds(10, 150, 120, 30);

        checkMasc3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc3.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc3.setText("FutVolei");
        checkMasc3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMasc3ActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc3);
        checkMasc3.setBounds(10, 180, 120, 30);

        checkMasc4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc4.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc4.setText("Volei");
        checkMasc4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMasc4ActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc4);
        checkMasc4.setBounds(10, 210, 120, 30);

        lblNome1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(116, 116, 116));
        lblNome1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNome1.setText("Cidade");
        jPanel3.add(lblNome1);
        lblNome1.setBounds(10, 280, 140, 14);

        checkMasc5.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc5.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc5.setText("Igaporã");
        checkMasc5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMasc5ActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc5);
        checkMasc5.setBounds(10, 300, 120, 30);

        checkMasc6.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc6.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc6.setText("Caetite");
        checkMasc6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMasc6ActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc6);
        checkMasc6.setBounds(10, 330, 120, 30);

        checkMasc7.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        checkMasc7.setForeground(new java.awt.Color(116, 116, 116));
        checkMasc7.setText("Guanambi");
        checkMasc7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkMasc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMasc7ActionPerformed(evt);
            }
        });
        jPanel3.add(checkMasc7);
        checkMasc7.setBounds(10, 360, 120, 30);

        lblNome2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(116, 116, 116));
        lblNome2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNome2.setText("Esportes");
        jPanel3.add(lblNome2);
        lblNome2.setBounds(10, 100, 140, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundoFiltro.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 260, 490);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 490));

        pnlEquipe7.setLayout(null);

        lblNJogadores6.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNJogadores6.setForeground(new java.awt.Color(116, 116, 116));
        lblNJogadores6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNJogadores6.setText("Nº de Jogadores: 12/21");
        pnlEquipe7.add(lblNJogadores6);
        lblNJogadores6.setBounds(10, 70, 290, 20);

        lblEnderecoEquipe6.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEnderecoEquipe6.setForeground(new java.awt.Color(116, 116, 116));
        lblEnderecoEquipe6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnderecoEquipe6.setText("Quadra, Rua abc 123, centro");
        pnlEquipe7.add(lblEnderecoEquipe6);
        lblEnderecoEquipe6.setBounds(10, 50, 290, 20);

        lblNomeDaEquipe6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNomeDaEquipe6.setForeground(new java.awt.Color(116, 116, 116));
        lblNomeDaEquipe6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeDaEquipe6.setText("Nome da equipe");
        pnlEquipe7.add(lblNomeDaEquipe6);
        lblNomeDaEquipe6.setBounds(10, 10, 140, 14);

        lblEsporteEquipe6.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEsporteEquipe6.setForeground(new java.awt.Color(116, 116, 116));
        lblEsporteEquipe6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEsporteEquipe6.setText("Esporte");
        pnlEquipe7.add(lblEsporteEquipe6);
        lblEsporteEquipe6.setBounds(10, 30, 140, 14);

        lblCidadeEquipe6.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCidadeEquipe6.setForeground(new java.awt.Color(116, 116, 116));
        lblCidadeEquipe6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidadeEquipe6.setText("Cidade");
        pnlEquipe7.add(lblCidadeEquipe6);
        lblCidadeEquipe6.setBounds(160, 30, 140, 14);

        fundo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        pnlEquipe7.add(fundo6);
        fundo6.setBounds(0, 0, 310, 100);

        getContentPane().add(pnlEquipe7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 310, 100));

        pnlEquipe6.setLayout(null);

        lblNJogadores5.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNJogadores5.setForeground(new java.awt.Color(116, 116, 116));
        lblNJogadores5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNJogadores5.setText("Nº de Jogadores: 12/21");
        pnlEquipe6.add(lblNJogadores5);
        lblNJogadores5.setBounds(10, 70, 290, 20);

        lblEnderecoEquipe5.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEnderecoEquipe5.setForeground(new java.awt.Color(116, 116, 116));
        lblEnderecoEquipe5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnderecoEquipe5.setText("Quadra, Rua abc 123, centro");
        pnlEquipe6.add(lblEnderecoEquipe5);
        lblEnderecoEquipe5.setBounds(10, 50, 290, 20);

        lblNomeDaEquipe5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNomeDaEquipe5.setForeground(new java.awt.Color(116, 116, 116));
        lblNomeDaEquipe5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeDaEquipe5.setText("Nome da equipe");
        pnlEquipe6.add(lblNomeDaEquipe5);
        lblNomeDaEquipe5.setBounds(10, 10, 140, 14);

        lblEsporteEquipe5.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEsporteEquipe5.setForeground(new java.awt.Color(116, 116, 116));
        lblEsporteEquipe5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEsporteEquipe5.setText("Esporte");
        pnlEquipe6.add(lblEsporteEquipe5);
        lblEsporteEquipe5.setBounds(10, 30, 140, 14);

        lblCidadeEquipe5.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCidadeEquipe5.setForeground(new java.awt.Color(116, 116, 116));
        lblCidadeEquipe5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidadeEquipe5.setText("Cidade");
        pnlEquipe6.add(lblCidadeEquipe5);
        lblCidadeEquipe5.setBounds(160, 30, 140, 14);

        fundo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        pnlEquipe6.add(fundo5);
        fundo5.setBounds(0, 0, 310, 100);

        getContentPane().add(pnlEquipe6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 310, 100));

        pnlEquipe5.setLayout(null);

        lblNJogadores4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNJogadores4.setForeground(new java.awt.Color(116, 116, 116));
        lblNJogadores4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNJogadores4.setText("Nº de Jogadores: 12/21");
        pnlEquipe5.add(lblNJogadores4);
        lblNJogadores4.setBounds(10, 70, 290, 20);

        lblEnderecoEquipe4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEnderecoEquipe4.setForeground(new java.awt.Color(116, 116, 116));
        lblEnderecoEquipe4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnderecoEquipe4.setText("Quadra, Rua abc 123, centro");
        pnlEquipe5.add(lblEnderecoEquipe4);
        lblEnderecoEquipe4.setBounds(10, 50, 290, 20);

        lblNomeDaEquipe4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNomeDaEquipe4.setForeground(new java.awt.Color(116, 116, 116));
        lblNomeDaEquipe4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeDaEquipe4.setText("Nome da equipe");
        pnlEquipe5.add(lblNomeDaEquipe4);
        lblNomeDaEquipe4.setBounds(10, 10, 140, 14);

        lblEsporteEquipe4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEsporteEquipe4.setForeground(new java.awt.Color(116, 116, 116));
        lblEsporteEquipe4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEsporteEquipe4.setText("Esporte");
        pnlEquipe5.add(lblEsporteEquipe4);
        lblEsporteEquipe4.setBounds(10, 30, 140, 14);

        lblCidadeEquipe4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCidadeEquipe4.setForeground(new java.awt.Color(116, 116, 116));
        lblCidadeEquipe4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidadeEquipe4.setText("Cidade");
        pnlEquipe5.add(lblCidadeEquipe4);
        lblCidadeEquipe4.setBounds(160, 30, 140, 14);

        fundo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        pnlEquipe5.add(fundo4);
        fundo4.setBounds(0, 0, 310, 100);

        getContentPane().add(pnlEquipe5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 310, 100));

        pnlEquipe4.setLayout(null);

        lblNJogadores2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNJogadores2.setForeground(new java.awt.Color(116, 116, 116));
        lblNJogadores2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNJogadores2.setText("Nº de Jogadores: 12/21");
        pnlEquipe4.add(lblNJogadores2);
        lblNJogadores2.setBounds(10, 70, 290, 20);

        lblEnderecoEquipe2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEnderecoEquipe2.setForeground(new java.awt.Color(116, 116, 116));
        lblEnderecoEquipe2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnderecoEquipe2.setText("Quadra, Rua abc 123, centro");
        pnlEquipe4.add(lblEnderecoEquipe2);
        lblEnderecoEquipe2.setBounds(10, 50, 290, 20);

        lblNomeDaEquipe2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNomeDaEquipe2.setForeground(new java.awt.Color(116, 116, 116));
        lblNomeDaEquipe2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeDaEquipe2.setText("Nome da equipe");
        pnlEquipe4.add(lblNomeDaEquipe2);
        lblNomeDaEquipe2.setBounds(10, 10, 140, 14);

        lblEsporteEquipe2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEsporteEquipe2.setForeground(new java.awt.Color(116, 116, 116));
        lblEsporteEquipe2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEsporteEquipe2.setText("Esporte");
        pnlEquipe4.add(lblEsporteEquipe2);
        lblEsporteEquipe2.setBounds(10, 30, 140, 14);

        lblCidadeEquipe2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCidadeEquipe2.setForeground(new java.awt.Color(116, 116, 116));
        lblCidadeEquipe2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidadeEquipe2.setText("Cidade");
        pnlEquipe4.add(lblCidadeEquipe2);
        lblCidadeEquipe2.setBounds(160, 30, 140, 14);

        fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        pnlEquipe4.add(fundo2);
        fundo2.setBounds(0, 0, 310, 100);

        getContentPane().add(pnlEquipe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 310, 100));

        pnlEquipe3.setLayout(null);

        lblNJogadores3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNJogadores3.setForeground(new java.awt.Color(116, 116, 116));
        lblNJogadores3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNJogadores3.setText("Nº de Jogadores: 12/21");
        pnlEquipe3.add(lblNJogadores3);
        lblNJogadores3.setBounds(10, 70, 290, 20);

        lblEnderecoEquipe3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEnderecoEquipe3.setForeground(new java.awt.Color(116, 116, 116));
        lblEnderecoEquipe3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnderecoEquipe3.setText("Quadra, Rua abc 123, centro");
        pnlEquipe3.add(lblEnderecoEquipe3);
        lblEnderecoEquipe3.setBounds(10, 50, 290, 20);

        lblNomeDaEquipe3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNomeDaEquipe3.setForeground(new java.awt.Color(116, 116, 116));
        lblNomeDaEquipe3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeDaEquipe3.setText("Nome da equipe");
        pnlEquipe3.add(lblNomeDaEquipe3);
        lblNomeDaEquipe3.setBounds(10, 10, 140, 14);

        lblEsporteEquipe3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEsporteEquipe3.setForeground(new java.awt.Color(116, 116, 116));
        lblEsporteEquipe3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEsporteEquipe3.setText("Esporte");
        pnlEquipe3.add(lblEsporteEquipe3);
        lblEsporteEquipe3.setBounds(10, 30, 140, 14);

        lblCidadeEquipe3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCidadeEquipe3.setForeground(new java.awt.Color(116, 116, 116));
        lblCidadeEquipe3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidadeEquipe3.setText("Cidade");
        pnlEquipe3.add(lblCidadeEquipe3);
        lblCidadeEquipe3.setBounds(160, 30, 140, 14);

        fundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        pnlEquipe3.add(fundo3);
        fundo3.setBounds(0, 0, 310, 100);

        getContentPane().add(pnlEquipe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 310, 100));

        pnlEquipe2.setLayout(null);

        lblNJogadores1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNJogadores1.setForeground(new java.awt.Color(116, 116, 116));
        lblNJogadores1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNJogadores1.setText("Nº de Jogadores: 12/21");
        pnlEquipe2.add(lblNJogadores1);
        lblNJogadores1.setBounds(10, 70, 290, 20);

        lblEnderecoEquipe1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEnderecoEquipe1.setForeground(new java.awt.Color(116, 116, 116));
        lblEnderecoEquipe1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnderecoEquipe1.setText("Quadra, Rua abc 123, centro");
        pnlEquipe2.add(lblEnderecoEquipe1);
        lblEnderecoEquipe1.setBounds(10, 50, 290, 20);

        lblNomeDaEquipe1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNomeDaEquipe1.setForeground(new java.awt.Color(116, 116, 116));
        lblNomeDaEquipe1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeDaEquipe1.setText("Nome da equipe");
        pnlEquipe2.add(lblNomeDaEquipe1);
        lblNomeDaEquipe1.setBounds(10, 10, 140, 14);

        lblEsporteEquipe1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEsporteEquipe1.setForeground(new java.awt.Color(116, 116, 116));
        lblEsporteEquipe1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEsporteEquipe1.setText("Esporte");
        pnlEquipe2.add(lblEsporteEquipe1);
        lblEsporteEquipe1.setBounds(10, 30, 140, 14);

        lblCidadeEquipe1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCidadeEquipe1.setForeground(new java.awt.Color(116, 116, 116));
        lblCidadeEquipe1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidadeEquipe1.setText("Cidade");
        pnlEquipe2.add(lblCidadeEquipe1);
        lblCidadeEquipe1.setBounds(160, 30, 140, 14);

        fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        pnlEquipe2.add(fundo1);
        fundo1.setBounds(0, 0, 310, 100);

        getContentPane().add(pnlEquipe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 310, 100));

        pnlEquipe1.setLayout(null);

        lblNJogadores.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblNJogadores.setForeground(new java.awt.Color(116, 116, 116));
        lblNJogadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNJogadores.setText("Nº de Jogadores: 12/21");
        pnlEquipe1.add(lblNJogadores);
        lblNJogadores.setBounds(10, 70, 290, 20);

        lblEnderecoEquipe.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEnderecoEquipe.setForeground(new java.awt.Color(116, 116, 116));
        lblEnderecoEquipe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnderecoEquipe.setText("Quadra, Rua abc 123, centro");
        pnlEquipe1.add(lblEnderecoEquipe);
        lblEnderecoEquipe.setBounds(10, 50, 290, 20);

        lblNomeDaEquipe.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNomeDaEquipe.setForeground(new java.awt.Color(116, 116, 116));
        lblNomeDaEquipe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNomeDaEquipe.setText("Nome da equipe");
        pnlEquipe1.add(lblNomeDaEquipe);
        lblNomeDaEquipe.setBounds(10, 10, 140, 14);

        lblEsporteEquipe.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblEsporteEquipe.setForeground(new java.awt.Color(116, 116, 116));
        lblEsporteEquipe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEsporteEquipe.setText("Esporte");
        pnlEquipe1.add(lblEsporteEquipe);
        lblEsporteEquipe.setBounds(10, 30, 140, 14);

        lblCidadeEquipe.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        lblCidadeEquipe.setForeground(new java.awt.Color(116, 116, 116));
        lblCidadeEquipe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidadeEquipe.setText("Cidade");
        pnlEquipe1.add(lblCidadeEquipe);
        lblCidadeEquipe.setBounds(160, 30, 140, 14);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        pnlEquipe1.add(fundo);
        fundo.setBounds(0, 0, 310, 100);

        getContentPane().add(pnlEquipe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 310, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-padrao.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMascActionPerformed

    private void checkMasc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMasc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMasc2ActionPerformed

    private void checkMasc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMasc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMasc1ActionPerformed

    private void checkMasc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMasc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMasc3ActionPerformed

    private void checkMasc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMasc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMasc4ActionPerformed

    private void checkMasc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMasc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMasc5ActionPerformed

    private void checkMasc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMasc6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMasc6ActionPerformed

    private void checkMasc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMasc7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkMasc7ActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCriarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarEquipeActionPerformed

    private void btnPesquisarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPerfilActionPerformed
        TelaPerfilVIEW j = new TelaPerfilVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnPesquisarPerfilActionPerformed

    private void btnPesquisarPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPesquisarActionPerformed
        TelaPesquisaVIEW j = new TelaPesquisaVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnPesquisarPesquisarActionPerformed

    private void btnPesquisarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarEquipeActionPerformed
        TelaEquipeVIEW j = new TelaEquipeVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnPesquisarEquipeActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisaVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisaVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPesquisarEquipe;
    private javax.swing.JButton btnPesquisarPerfil;
    private javax.swing.JButton btnPesquisarPesquisar;
    private javax.swing.JCheckBox checkMasc;
    private javax.swing.JCheckBox checkMasc1;
    private javax.swing.JCheckBox checkMasc2;
    private javax.swing.JCheckBox checkMasc3;
    private javax.swing.JCheckBox checkMasc4;
    private javax.swing.JCheckBox checkMasc5;
    private javax.swing.JCheckBox checkMasc6;
    private javax.swing.JCheckBox checkMasc7;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundo1;
    private javax.swing.JLabel fundo2;
    private javax.swing.JLabel fundo3;
    private javax.swing.JLabel fundo4;
    private javax.swing.JLabel fundo5;
    private javax.swing.JLabel fundo6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCidadeEquipe;
    private javax.swing.JLabel lblCidadeEquipe1;
    private javax.swing.JLabel lblCidadeEquipe2;
    private javax.swing.JLabel lblCidadeEquipe3;
    private javax.swing.JLabel lblCidadeEquipe4;
    private javax.swing.JLabel lblCidadeEquipe5;
    private javax.swing.JLabel lblCidadeEquipe6;
    private javax.swing.JLabel lblEnderecoEquipe;
    private javax.swing.JLabel lblEnderecoEquipe1;
    private javax.swing.JLabel lblEnderecoEquipe2;
    private javax.swing.JLabel lblEnderecoEquipe3;
    private javax.swing.JLabel lblEnderecoEquipe4;
    private javax.swing.JLabel lblEnderecoEquipe5;
    private javax.swing.JLabel lblEnderecoEquipe6;
    private javax.swing.JLabel lblEsporteEquipe;
    private javax.swing.JLabel lblEsporteEquipe1;
    private javax.swing.JLabel lblEsporteEquipe2;
    private javax.swing.JLabel lblEsporteEquipe3;
    private javax.swing.JLabel lblEsporteEquipe4;
    private javax.swing.JLabel lblEsporteEquipe5;
    private javax.swing.JLabel lblEsporteEquipe6;
    private javax.swing.JLabel lblNJogadores;
    private javax.swing.JLabel lblNJogadores1;
    private javax.swing.JLabel lblNJogadores2;
    private javax.swing.JLabel lblNJogadores3;
    private javax.swing.JLabel lblNJogadores4;
    private javax.swing.JLabel lblNJogadores5;
    private javax.swing.JLabel lblNJogadores6;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNomeDaEquipe;
    private javax.swing.JLabel lblNomeDaEquipe1;
    private javax.swing.JLabel lblNomeDaEquipe2;
    private javax.swing.JLabel lblNomeDaEquipe3;
    private javax.swing.JLabel lblNomeDaEquipe4;
    private javax.swing.JLabel lblNomeDaEquipe5;
    private javax.swing.JLabel lblNomeDaEquipe6;
    private javax.swing.JPanel menuTopo;
    private javax.swing.JPanel pnlEquipe1;
    private javax.swing.JPanel pnlEquipe2;
    private javax.swing.JPanel pnlEquipe3;
    private javax.swing.JPanel pnlEquipe4;
    private javax.swing.JPanel pnlEquipe5;
    private javax.swing.JPanel pnlEquipe6;
    private javax.swing.JPanel pnlEquipe7;
    // End of variables declaration//GEN-END:variables
}
