/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author netoi
 */
public class TelaEquipeVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public TelaEquipeVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTopo = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        btnEquipePerfil = new javax.swing.JButton();
        btnEquipePesquisar = new javax.swing.JButton();
        btnEquipeEditarEquipe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnEditarPerfil3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        btnEditarPerfil2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnEditarPerfil1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblCidade1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblIdade1 = new javax.swing.JLabel();
        lblEsportes1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblEsportes = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblCidade2 = new javax.swing.JLabel();
        lblCidade3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblCidade4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuTopo.setLayout(null);

        btnHome.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        menuTopo.add(btnHome);
        btnHome.setBounds(30, 10, 100, 30);

        Logo.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logo.setText("ArenaAPP");
        menuTopo.add(Logo);
        Logo.setBounds(40, 10, 110, 30);

        btnEquipePerfil.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnEquipePerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnEquipePerfil.setText("Perfil");
        btnEquipePerfil.setBorderPainted(false);
        btnEquipePerfil.setContentAreaFilled(false);
        btnEquipePerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquipePerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipePerfilActionPerformed(evt);
            }
        });
        menuTopo.add(btnEquipePerfil);
        btnEquipePerfil.setBounds(832, 10, 90, 30);

        btnEquipePesquisar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnEquipePesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnEquipePesquisar.setText("Pesquisar");
        btnEquipePesquisar.setBorderPainted(false);
        btnEquipePesquisar.setContentAreaFilled(false);
        btnEquipePesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquipePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipePesquisarActionPerformed(evt);
            }
        });
        menuTopo.add(btnEquipePesquisar);
        btnEquipePesquisar.setBounds(540, 10, 130, 30);

        btnEquipeEditarEquipe.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnEquipeEditarEquipe.setForeground(new java.awt.Color(255, 255, 255));
        btnEquipeEditarEquipe.setText("Editar Equipe");
        btnEquipeEditarEquipe.setBorderPainted(false);
        btnEquipeEditarEquipe.setContentAreaFilled(false);
        btnEquipeEditarEquipe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEquipeEditarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquipeEditarEquipeActionPerformed(evt);
            }
        });
        menuTopo.add(btnEquipeEditarEquipe);
        btnEquipeEditarEquipe.setBounds(680, 10, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-menu-topo.png"))); // NOI18N
        menuTopo.add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 50);

        getContentPane().add(menuTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnEditarPerfil3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnEditarPerfil3.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil3.setText("Editar");
        btnEditarPerfil3.setBorderPainted(false);
        btnEditarPerfil3.setContentAreaFilled(false);
        btnEditarPerfil3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPerfil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfil3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarPerfil3);
        btnEditarPerfil3.setBounds(50, 210, 120, 20);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao120x30.png"))); // NOI18N
        jPanel3.add(jLabel23);
        jLabel23.setBounds(50, 200, 120, 40);

        btnEditarPerfil2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnEditarPerfil2.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil2.setText("Instagram");
        btnEditarPerfil2.setBorderPainted(false);
        btnEditarPerfil2.setContentAreaFilled(false);
        btnEditarPerfil2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPerfil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfil2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarPerfil2);
        btnEditarPerfil2.setBounds(180, 210, 120, 20);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao120x30.png"))); // NOI18N
        jPanel3.add(jLabel22);
        jLabel22.setBounds(180, 200, 120, 40);

        btnEditarPerfil1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnEditarPerfil1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil1.setText("Whatsapp");
        btnEditarPerfil1.setBorderPainted(false);
        btnEditarPerfil1.setContentAreaFilled(false);
        btnEditarPerfil1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfil1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarPerfil1);
        btnEditarPerfil1.setBounds(310, 210, 120, 20);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao120x30.png"))); // NOI18N
        jPanel3.add(jLabel21);
        jLabel21.setBounds(310, 200, 120, 40);

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(116, 116, 116));
        jLabel16.setText("Dono:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(30, 20, 50, 20);

        lblCidade1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCidade1.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblCidade1);
        lblCidade1.setBounds(80, 20, 130, 20);

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(116, 116, 116));
        jLabel17.setText("Admistrador:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(30, 50, 90, 20);

        lblIdade1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblIdade1.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblIdade1);
        lblIdade1.setBounds(110, 50, 120, 20);

        lblEsportes1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblEsportes1.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblEsportes1);
        lblEsportes1.setBounds(30, 180, 390, 20);

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(116, 116, 116));
        jLabel15.setText("Local");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(30, 160, 130, 15);

        lblEsportes.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblEsportes.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblEsportes);
        lblEsportes.setBounds(30, 130, 190, 20);

        lblIdade.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblIdade);
        lblIdade.setBounds(290, 80, 130, 20);

        lblCidade.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblCidade);
        lblCidade.setBounds(80, 80, 130, 20);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(116, 116, 116));
        jLabel13.setText("Dias de pratica");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 110, 130, 15);

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(116, 116, 116));
        jLabel11.setText("Esporte:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(230, 80, 50, 20);

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(116, 116, 116));
        jLabel12.setText("Cidade:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 80, 50, 20);

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(116, 116, 116));
        jLabel18.setText("ID");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(290, 20, 20, 20);

        lblCidade2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCidade2.setForeground(new java.awt.Color(116, 116, 116));
        lblCidade2.setText("00000000");
        jPanel3.add(lblCidade2);
        lblCidade2.setBounds(320, 20, 70, 20);

        lblCidade3.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCidade3.setForeground(new java.awt.Color(116, 116, 116));
        lblCidade3.setText("00000000");
        jPanel3.add(lblCidade3);
        lblCidade3.setBounds(320, 50, 70, 20);

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(116, 116, 116));
        jLabel19.setText("ID");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(290, 50, 20, 20);

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(116, 116, 116));
        jLabel20.setText("Jogadores:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(230, 110, 70, 20);

        lblCidade4.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCidade4.setForeground(new java.awt.Color(116, 116, 116));
        lblCidade4.setText("0/21");
        jPanel3.add(lblCidade4);
        lblCidade4.setBounds(230, 130, 70, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-dados-user.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 0, 440, 250);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 440, 250));

        jPanel2.setLayout(null);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "POS", "NOME", "CIDADE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 420, 440);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-user-time.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 420, 440);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 420, 440));

        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escudo-placeholder150x150.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 154, 154);

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(116, 116, 116));
        jLabel3.setText("Nome Equipe");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(174, 16, 248, 15);

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(116, 116, 116));
        jLabel5.setText("Sobre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(174, 37, 248, 15);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 440, 170);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 440, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-padrao.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarPerfil1ActionPerformed

    private void btnEditarPerfil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarPerfil2ActionPerformed

    private void btnEditarPerfil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfil3ActionPerformed
        FormEditarEquipeVIEW j = new FormEditarEquipeVIEW();
        j.setVisible(true);
        
    }//GEN-LAST:event_btnEditarPerfil3ActionPerformed

    private void btnEquipePerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipePerfilActionPerformed
        TelaPerfilVIEW j = new TelaPerfilVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnEquipePerfilActionPerformed

    private void btnEquipePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipePesquisarActionPerformed
        TelaPesquisaVIEW j = new TelaPesquisaVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnEquipePesquisarActionPerformed

    private void btnEquipeEditarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquipeEditarEquipeActionPerformed
        FormEditarEquipeVIEW j = new FormEditarEquipeVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnEquipeEditarEquipeActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEquipeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEquipeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEquipeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEquipeVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEquipeVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton btnEditarPerfil1;
    private javax.swing.JButton btnEditarPerfil2;
    private javax.swing.JButton btnEditarPerfil3;
    private javax.swing.JButton btnEquipeEditarEquipe;
    private javax.swing.JButton btnEquipePerfil;
    private javax.swing.JButton btnEquipePesquisar;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidade1;
    private javax.swing.JLabel lblCidade2;
    private javax.swing.JLabel lblCidade3;
    private javax.swing.JLabel lblCidade4;
    private javax.swing.JLabel lblEsportes;
    private javax.swing.JLabel lblEsportes1;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblIdade1;
    private javax.swing.JPanel menuTopo;
    // End of variables declaration//GEN-END:variables
}
