/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import REPOSITORY.BancoDeDados;
import REPOSITORY.UsuarioRepository;
import SERVICES.UsuarioService;
import javax.swing.JOptionPane;

/**
 *
 * @author netoi
 */
public class TelaPerfilVIEW extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public TelaPerfilVIEW() {
        initComponents();
        UsuarioRepository repository = new UsuarioRepository();
        
        if (!BancoDeDados.usuarioLogado.isLogado()) {
            lblSair.setVisible(false);
            lblEditar.setVisible(false);
            lblExcluir.setVisible(false);
            btnSair.setVisible(false);
            btnEditar.setVisible(false);
            btnExcluir.setVisible(false);
        }
        
        lblNome.setText(BancoDeDados.usuarioLogado.getNome());
        lblCidade.setText(BancoDeDados.usuarioLogado.getCidade());
        lblIdUsuario.setText(String.valueOf(BancoDeDados.usuarioLogado.getIdUsuario()));
        lblIdade.setText(String.valueOf(repository.getIdade()));
        lblBiografia.setText(BancoDeDados.usuarioLogado.getDescricao());
        String[] esportes = BancoDeDados.usuarioLogado.getEsporte();
        lblFutsal.setText(esportes[0]);
        lblFutebol.setText(esportes[1]);
        lblFutVolei.setText(esportes[2]);
        lblVolei.setText(esportes[3]);
        lblBasquete.setText(esportes[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTopo = new javax.swing.JPanel();
        btnPerfilEditarPerfil = new javax.swing.JButton();
        btnPerfilPesquisar = new javax.swing.JButton();
        btnPerfilEquipe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        lblExcluir = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblSair = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        lblEditar = new javax.swing.JLabel();
        lblVolei = new javax.swing.JLabel();
        lblBasquete = new javax.swing.JLabel();
        lblFutVolei = new javax.swing.JLabel();
        lblFutebol = new javax.swing.JLabel();
        lblFutsal = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBiografia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuTopo.setLayout(null);

        btnPerfilEditarPerfil.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnPerfilEditarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfilEditarPerfil.setText("Perfil");
        btnPerfilEditarPerfil.setBorderPainted(false);
        btnPerfilEditarPerfil.setContentAreaFilled(false);
        btnPerfilEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfilEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilEditarPerfilActionPerformed(evt);
            }
        });
        menuTopo.add(btnPerfilEditarPerfil);
        btnPerfilEditarPerfil.setBounds(812, 10, 130, 30);

        btnPerfilPesquisar.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnPerfilPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfilPesquisar.setText("Pesquisar");
        btnPerfilPesquisar.setBorderPainted(false);
        btnPerfilPesquisar.setContentAreaFilled(false);
        btnPerfilPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfilPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilPesquisarActionPerformed(evt);
            }
        });
        menuTopo.add(btnPerfilPesquisar);
        btnPerfilPesquisar.setBounds(540, 10, 130, 30);

        btnPerfilEquipe.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        btnPerfilEquipe.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfilEquipe.setText("Equipe");
        btnPerfilEquipe.setBorderPainted(false);
        btnPerfilEquipe.setContentAreaFilled(false);
        btnPerfilEquipe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfilEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilEquipeActionPerformed(evt);
            }
        });
        menuTopo.add(btnPerfilEquipe);
        btnPerfilEquipe.setBounds(680, 10, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-menu-topo.png"))); // NOI18N
        menuTopo.add(jLabel2);
        jLabel2.setBounds(0, 0, 960, 50);

        getContentPane().add(menuTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnExcluir.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btnExcluir);
        btnExcluir.setBounds(300, 170, 120, 20);

        lblExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao120x30.png"))); // NOI18N
        jPanel3.add(lblExcluir);
        lblExcluir.setBounds(300, 160, 120, 40);

        btnSair.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("Sair");
        btnSair.setBorderPainted(false);
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel3.add(btnSair);
        btnSair.setBounds(30, 210, 120, 20);

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao120x30.png"))); // NOI18N
        jPanel3.add(lblSair);
        lblSair.setBounds(30, 200, 120, 40);

        btnEditar.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar);
        btnEditar.setBounds(300, 210, 120, 20);

        lblEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botao120x30.png"))); // NOI18N
        jPanel3.add(lblEditar);
        lblEditar.setBounds(300, 200, 120, 40);

        lblVolei.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblVolei.setForeground(new java.awt.Color(116, 116, 116));
        lblVolei.setText("Volei");
        jPanel3.add(lblVolei);
        lblVolei.setBounds(30, 130, 190, 20);

        lblBasquete.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblBasquete.setForeground(new java.awt.Color(116, 116, 116));
        lblBasquete.setText("Basquete");
        jPanel3.add(lblBasquete);
        lblBasquete.setBounds(30, 150, 190, 20);

        lblFutVolei.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblFutVolei.setForeground(new java.awt.Color(116, 116, 116));
        lblFutVolei.setText("FutVolei");
        jPanel3.add(lblFutVolei);
        lblFutVolei.setBounds(30, 110, 190, 20);

        lblFutebol.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblFutebol.setForeground(new java.awt.Color(116, 116, 116));
        lblFutebol.setText("Futebol");
        jPanel3.add(lblFutebol);
        lblFutebol.setBounds(30, 90, 190, 20);

        lblFutsal.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblFutsal.setForeground(new java.awt.Color(116, 116, 116));
        lblFutsal.setText("Futsal");
        jPanel3.add(lblFutsal);
        lblFutsal.setBounds(30, 70, 190, 20);

        lblIdade.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblIdade.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblIdade);
        lblIdade.setBounds(270, 20, 130, 20);

        lblCidade.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(116, 116, 116));
        jPanel3.add(lblCidade);
        lblCidade.setBounds(80, 20, 130, 20);

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(116, 116, 116));
        jLabel13.setText("Esportes praticados:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 50, 130, 15);

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(116, 116, 116));
        jLabel11.setText("Idade:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(232, 20, 40, 20);

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(116, 116, 116));
        jLabel12.setText("Cidade:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 20, 50, 20);

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(116, 116, 116));
        jLabel15.setText("ID");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(30, 180, 20, 20);

        lblIdUsuario.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblIdUsuario.setForeground(new java.awt.Color(116, 116, 116));
        lblIdUsuario.setText("00000000");
        jPanel3.add(lblIdUsuario);
        lblIdUsuario.setBounds(60, 180, 130, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-dados-user.png"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 0, 440, 250);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 440, 250));

        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(116, 116, 116));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sem equipe");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(60, 380, 310, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escudo-placeholder.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 20, 330, 330);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-user-time.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 0, 420, 440);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 420, 440));

        jPanel1.setLayout(null);

        lblBiografia.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblBiografia.setForeground(new java.awt.Color(116, 116, 116));
        lblBiografia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBiografia.setText("a");
        lblBiografia.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lblBiografia);
        lblBiografia.setBounds(180, 60, 250, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boy-profile.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 154, 154);

        lblNome.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(116, 116, 116));
        lblNome.setText("Nome Completo");
        jPanel1.add(lblNome);
        lblNome.setBounds(174, 16, 248, 15);

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(116, 116, 116));
        jLabel5.setText("Sobre");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(174, 37, 248, 15);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-usuario.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 440, 170);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 440, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo-padrao.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        FormEditarPerfilVIEW j = new FormEditarPerfilVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPerfilEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilEditarPerfilActionPerformed
        FormEditarPerfilVIEW j = new FormEditarPerfilVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnPerfilEditarPerfilActionPerformed

    private void btnPerfilPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilPesquisarActionPerformed
        TelaPesquisaVIEW j = new TelaPesquisaVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnPerfilPesquisarActionPerformed

    private void btnPerfilEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilEquipeActionPerformed
        TelaPerfilVIEW j = new TelaPerfilVIEW();
        this.dispose();
        j.setVisible(true);
    }//GEN-LAST:event_btnPerfilEquipeActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        UsuarioService service = new UsuarioService();
        service.sair(BancoDeDados.usuarioLogado);
        TelaInicialVIEW j = new TelaInicialVIEW();
        this.dispose();
        j.setVisible(true);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        int confirmar = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja excluir sua conta?", "Confirmar Exclusão",JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            UsuarioService service = new UsuarioService();
            service.excluir(BancoDeDados.usuarioLogado);
            JOptionPane.showMessageDialog(rootPane, "Sua conta foi deletada");
            TelaInicialVIEW j = new TelaInicialVIEW();
            this.dispose();
            j.setVisible(true);
        }
            
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerfilVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerfilVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPerfilEditarPerfil;
    private javax.swing.JButton btnPerfilEquipe;
    private javax.swing.JButton btnPerfilPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBasquete;
    private javax.swing.JLabel lblBiografia;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEditar;
    private javax.swing.JLabel lblExcluir;
    private javax.swing.JLabel lblFutVolei;
    private javax.swing.JLabel lblFutebol;
    private javax.swing.JLabel lblFutsal;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblVolei;
    private javax.swing.JPanel menuTopo;
    // End of variables declaration//GEN-END:variables
}
